/* ============================================================
   EmTech PC Tips — tips-data.js
   All tip content lives here. Add a new tip by adding a new
   object to the TIPS array — the page renders it automatically.
   Fields:
     title       string
     cat         one of: mac, speed, windows, gaming, cleaning, maintenance, hardware, security
     difficulty  1 (easy) | 2 (medium) | 3 (advanced)
     time        short estimate, e.g. "2 min"
     win         "Win 10/11" | "All versions" etc. (shown in the card footer)
     description string  (the short pitch)
     steps       array of step strings (rendered as a list)
   ============================================================ */

const TIPS = [
  {
    title: "Disable startup bloat",
    cat: "speed",
    difficulty: 1,
    time: "2 min",
    win: "Win 10 / 11",
    description: "Every app that launches at boot slows your PC down. Most don't need to.",
    steps: [
      "Press Ctrl + Shift + Esc to open Task Manager",
      "Go to the Startup apps tab (Startup in Win 10)",
      "Right-click anything non-essential and choose Disable",
      "Restart to see the faster boot",
    ],
  },
  {
    title: "Switch the power plan to Best Performance",
    cat: "speed",
    difficulty: 1,
    time: "1 min",
    win: "Win 10 / 11",
    description: "The default Balanced plan throttles the CPU to save power. On a desktop, just use full performance.",
    steps: [
      "Windows key, type 'Power Plan' to search",
      "Open 'Choose a power plan' from Control Panel results",
      "Select High performance",
      "On Win 11: Settings → System → Power → Power mode → Best performance",
    ],
  },
  {
    title: "Move your OS or games to an SSD",
    cat: "hardware",
    difficulty: 2,
    time: "1 hr",
    win: "Any",
    description: "HDD → SSD is the single biggest speed upgrade you can make. Boot times go from minutes to seconds.",
    steps: [
      "Buy a SATA or NVMe SSD (500 GB+ if going for OS + games)",
      "Use the SSD maker's cloning software (Samsung, Crucial, WD all have free tools) to clone your drive",
      "Swap the drives (or set the SSD as the first boot device in BIOS)",
      "Verify it boots, then shred and reuse the old HDD for storage",
    ],
  },
  {
    title: "Upgrade your RAM (and match it)",
    cat: "hardware",
    difficulty: 2,
    time: "30 min",
    win: "Any",
    description: "16 GB is the comfortable minimum for modern Windows use. Always buy matched pairs for dual-channel speed.",
    steps: [
      "Check what you have: open Task Manager → Performance → Memory",
      "Note the type (DDR4 / DDR5), speed, and how many slots are free",
      "Buy an identical stick for dual-channel, or a matched 2×16 GB kit",
      "Power off, unplug, push the side clips and drop the new RAM in; one firm click means it's seated",
    ],
  },
  {
    title: "Stop Windows updates at odd hours",
    cat: "windows",
    difficulty: 1,
    time: "3 min",
    win: "Win 10 / 11",
    description: "Updates restarting your PC while you're mid-game is a real thing. Set Active Hours so Windows knows when you're working.",
    steps: [
      "Settings → Windows Update → Advance options → Active hours",
      "Set a window that covers when you actually use the PC",
      "For more control: pause updates for up to 5 weeks any time",
    ],
  },
  {
    title: "Fix a PC that overheats and fans like a jet engine",
    cat: "maintenance",
    difficulty: 2,
    time: "45 min",
    win: "Any",
    description: "Loud fans usually mean dust, not a failing fan. A clean-out often fixes half of all 'my PC is slow' tickets.",
    steps: [
      "Power off and unplug. Open the case side panel",
      "Blow dust out with compressed air in short bursts (PSU first, then fans, then heatsink fins)",
      "Hold fan blades still while blowing — spinning them backfired can damage the motor",
      "Reseat RAM and check for loose cables on the way back in",
      "Reassemble, boot, and check temps in HWiNFO64",
    ],
  },
  {
    title: "Lower Windows transparency and animation effects",
    cat: "windows",
    difficulty: 1,
    time: "2 min",
    win: "Win 10 / 11",
    description: "Transparency and animations eat GPU and CPU on modest hardware. Turning them off makes everything feel snappier.",
    steps: [
      "Settings → Personalisation → Colours → turn off 'Transparency effects'",
      "Settings → Accessibility → Visual effects → turn off animation effects",
      "Optional: win+r → sysdm.cpl → Advanced → Performance → 'Adjust for best performance'",
    ],
  },
  {
    title: "Clean up temp files and browser cache properly",
    cat: "cleaning",
    difficulty: 1,
    time: "5 min",
    win: "Win 10 / 11",
    description: "Temp files and caches pile up gigabytes over months. They're safe to delete — that's what they're for.",
    steps: [
      "Settings → System → Storage → Temporary files → tick what you want and Remove files",
      "Also: win+r → %temp% → Ctrl+A → Delete (skip files in use)",
      "In each browser: Settings → Privacy → Clear browsing data → Cached images and files",
    ],
  },
  {
    title: "Let Windows' Storage Sense do the work for you",
    cat: "cleaning",
    difficulty: 1,
    time: "2 min",
    win: "Win 10 / 11",
    description: "Fully-automated junk cleanup. Turn it on once and forget about disk bloat until your next OS install.",
    steps: [
      "Settings → System → Storage → turn on Storage Sense",
      "Click 'Storage Sense' again to set when it runs (daily / weekly / monthly)",
      "Enable 'Delete files in Recycle Bin after 30 days' and 'Download folder cleanup'",
    ],
  },
  {
    title: "Uninstall the apps you never use",
    cat: "cleaning",
    difficulty: 1,
    time: "10 min",
    win: "Win 10 / 11",
    description: "Every installed app is small overhead — background services, update checks, context-menu entries. Remove what you don't open.",
    steps: [
      "Settings → Apps → Installed apps",
      "Sort by size — the biggest offenders are usually games you've abandoned",
      "Uninstall anything you haven't opened in 6 months",
      "Use the built-in optional-features list to remove bloat you don't use (Xbox extras, sample apps)",
    ],
  },
  {
    title: "Check for driver updates (in the right order)",
    cat: "maintenance",
    difficulty: 1,
    time: "15 min",
    win: "Any",
    description: "Stale or wrong drivers cause crashes, audio glitches, and odd lag. Update the GPU first — it's the one that matters most.",
    steps: [
      "GPU: use the maker's tool (NVIDIA GeForce Experience / AMD Adrenalin / Intel DSA) — not Windows Update for this",
      "Chipset + audio + network: the laptop/motherboard maker's support page is the only safe source",
      "Avoid third-party 'driver updaters' — they're mostly adware",
    ],
  },
  {
    title: "Run a disk health check before it's too late",
    cat: "maintenance",
    difficulty: 2,
    time: "15 min",
    win: "Win 10 / 11",
    description: "Drives fail suddenly. A 10-minute monthly check tells you when to back up and replace before the data is gone.",
    steps: [
      "Task Manager → Performance → Storage → check 'Health' (or use CrystalDiskInfo for full S.M.A.R.T. data)",
      "Any re-allocated sectors, pending sectors, or bad sectors = back everything up NOW",
      "SSDs: check 'Wear Leveling Count' — under 90% is fine, below 50% plan a replacement",
      "Run 'chkdsk C:' from an admin command prompt for a full scan (takes a while, do it overnight)",
    ],
  },
  {
    title: "Back up properly (3-2-1 rule)",
    cat: "security",
    difficulty: 2,
    time: "30 min",
    win: "Any",
    description: "Three copies, two different media, one off-site. It's boring — until you need it. Set it up once.",
    steps: [
      "Enable Windows File History or use a NAS / external drive (copy #1 + #2)",
      "Add a cloud backup for your documents folder (OneDrive, Google Drive, or Backblaze B2)",
      "For important projects, keep a second copy on a USB stick you store elsewhere",
      "Test a restore once a year — a backup you can't restore isn't a backup",
    ],
  },
  {
    title: "Stop games stuttering — the 5-point checklist",
    cat: "gaming",
    difficulty: 1,
    time: "15 min",
    win: "Win 10 / 11",
    description: "Most 'random lag spikes' trace back to one of five mundane causes. Knock them all out.",
    steps: [
      "GPU driver is current (make it a clean install with DDU if stutter persists)",
      "Game files intact / verified (Steam, EA, Epic all have a 'verify' button)",
      "DirectX / VCRedist packs are installed",
      "No overlays fighting each other (Steam + Discord + GeForce Experience = pick one)",
      "Disable Game Bar and Game DVR: Settings → Gaming → off both",
    ],
  },
  {
    title: "Raise your effective FPS with Windows Game Mode",
    cat: "gaming",
    difficulty: 1,
    time: "1 min",
    win: "Win 10 / 11",
    description: "Game Mode tells Windows to prioritise the game process and quiet notifications. Leave it on, always.",
    steps: [
      "Settings → Gaming → Game Mode → keep it ON",
      "Same page → Background processes → 'Limit background bandwidth' (on slow connections)",
      "In Task Manager, pin your game to a specific CPU core group if you have a hybrid CPU (P-cores vs E-cores) via the GPU's affinity settings",
    ],
  },
  {
    title: "Reduce input lag in competitive games",
    cat: "gaming",
    difficulty: 2,
    time: "20 min",
    win: "Win 10 / 11",
    description: "Millisecond matters in FPS games. Cut anything between your hand and the screen.",
    steps: [
      "Change monitor refresh rate: Windows → Screen → Advanced display → set to the monitor's native rate (often hidden at 60 Hz by default)",
      "Set GPU power management to 'Prefer Maximum Performance'",
      "In-game: uncap FPS to your refresh rate or go slightly higher",
      "Use a wired mouse if you can; 2.4 GHz wireless is fine, Bluetooth is not for competitive play",
    ],
  },
  {
    title: "Hardening: accounts, updates, and the firewall",
    cat: "security",
    difficulty: 1,
    time: "20 min",
    win: "Win 10 / 11",
    description: "The default Windows firewalls work. What most people skip is the 20 minutes of account hygiene that prevents 90% of incidents.",
    steps: [
      "Use a unique password per critical account, in a password manager (Bitwarden, 1Password, or the built-in Windows Credential Manager)",
      "Turn on Windows Hello (PIN / face) for daily login, keep the real password as your emergency fallback",
      "Check 'Use dynamic updates' and 'Automatic (recommended)' are both on under Windows Update",
      "In Settings → Accounts → Sign-in options, review which apps can start you up",
    ],
  },
  {
    title: "Kill shady 'PC optimizer' software",
    cat: "security",
    difficulty: 1,
    time: "10 min",
    win: "Any",
    description: "Half of every 'PC repair' product in the world is useless or actively harmful. There is no magic pill that makes Windows faster.",
    steps: [
      "If a program is nagging you about 'errors', 'registry problems', or 'RAM issues' — uninstall it",
      "Registry cleaners are scams: the Windows registry is not your hard drive, and 'optimising' it can break things",
      "The free, built-in tools (sfc /scannow, DISM, Disk Cleanup, Storage Sense) do everything those apps do, better",
    ],
  },
  {
    title: "Repair corrupted system files",
    cat: "maintenance",
    difficulty: 2,
    time: "30 min",
    win: "Win 10 / 11",
    description: "A slow, glitchy PC that won't update? Corrupted system files are usually the cause. Two commands fix most of it.",
    steps: [
      "Open Command Prompt as Administrator",
      "Run: DISM /Online /Cleanup-Image /RestoreHealth (waits a few minutes)",
      "Then run: sfc /scannow (about 15 minutes)",
      "Restart. Re-run sfc if it reports files it couldn't fix",
    ],
  },
  {
    title: "Stop your PC from sleep-glitching your network",
    cat: "windows",
    difficulty: 2,
    time: "10 min",
    win: "Win 10 / 11",
    description: "Ethernet that drops right after wake-from-sleep, or Wi-Fi that needs a manual reconnect — it's the NIC trying to save power",
    steps: [
      "Device Manager → Network adapters → your NIC → Properties → Power Management",
      "Uncheck 'Allow the computer to turn off this device to save power'",
      "Also under the same NIC → Advanced tab, set 'Green Ethernet' and 'Energy Efficient Ethernet' to Disabled",
    ],
  },
  {
    title: "Know your BIOS settings (the 5 that matter)",
    cat: "hardware",
    difficulty: 3,
    time: "20 min",
    win: "Any",
    description: "Most of the speed potential in a PC is already there — it's locked in the BIOS/UEFI. Five settings unlock most of it.",
    steps: [
      "Enter UEFI (usually F2 / DEL at boot). XMP/EXPO: enable it or your RAM runs at 2133 MHz instead of its rated speed",
      "Resizable BAR (Above 4G): on for GPU",
      "C-States: off if you do low-latency work",
      "Boot order: put your SSD first",
      "Enable virtualisation (VT-x / SVM) only if you use VMs or Android emulators — off is safer otherwise",
    ],
  },
  {
    title: "Protect against ransomware before it's too late",
    cat: "security",
    difficulty: 2,
    time: "20 min",
    win: "Win 10 / 11",
    description: "Ransomware that you can't restore from is the only data loss that really matters. VBS + Controlled Folder Access + a backup = you're almost unkillable.",
    steps: [
      "Turn on Windows Defender's 'Controlled folder access': Settings → Privacy & Security → Windows Security → Virus & threat protection → Ransomware protection → on",
      "Enable 'Memory integrity' (VBS) under Device security — yes, it has a tiny game FPS cost on old hardware, it's worth it",
      "Keep the 3-2-1 backup from the earlier tip — that's the thing that actually saves you",
    ],
  },
  {
    title: "Make Windows Search actually useful again",
    cat: "windows",
    difficulty: 1,
    time: "5 min",
    win: "Win 10 / 11",
    description: "When the Start menu search is slow or returns garbage, it's usually just the index and a few settings to fix.",
    steps: [
      "Settings → Search → 'Search Windows' → turn off 'Search online and sources beyond Windows' if you don't want web results",
      "Settings → Search → 'Searching Windows' → Advanced index options → Rebuild (5–20 min one-off)",
      "Exclude the folders you know are search-killers (game install dirs, node_modules, virtual machine disks)",
    ],
  },
  {
    title: "Save your games the right way",
    cat: "gaming",
    difficulty: 1,
    time: "5 min",
    win: "Any",
    description: "The #1 cause of 'I lost 200 hours of progress' is not a disk failure — it's saves living somewhere you didn't think to back up.",
    steps: [
      "Find where each game saves: most Steam games in %userprofile%\\AppData\\Local\\ or Documents",
      "Copy your whole Documents\\My Games (or the game's actual save folder) monthly to an external drive",
      "For Steam: enable Cloud Sync for games that support it — extra copy = extra safety",
    ],
  },
  {
    title: "Make your desktop feel like a Mac (without the price)",
    cat: "windows",
    difficulty: 1,
    time: "15 min",
    win: "Win 10 / 11",
    description: "Most Windows 'looks bad' complaints are just missing a few settings. A 15-minute pass makes it look dramatically cleaner.",
    steps: [
      "Settings → Personalisation → Colours → pick a base colour, turn on 'Accent colour' auto",
      "Turn off 'Transparency effects' for a flatter, cleaner look (and it's faster on weak GPUs too)",
      "Settings → Personalisation → Fonts → install a modern one (Inter, Segoe UI Variable, or JetBrains for a technical feel)",
      "Taskbar: right-click → Taskbar settings → turn off 'Combine taskbar buttons ever' and move to centre",
    ],
  },
  {
    title: "Fix 'My PC is slow all of a sudden' — the order of attack",
    cat: "speed",
    difficulty: 1,
    time: "15 min",
    win: "Win 10 / 11",
    description: "When a fast PC suddenly crawls, it's almost always one of four things. Check them in this order.",
    steps: [
      "1. Task Manager → Performance: is the Disk at 100%? (that's your HDD or a dying drive — the answer)",
      "2. Processes tab sorted by Memory or CPU: is something you don't recognise eating resources?",
      "3. Did a Windows Update land last night? Sometimes a bad driver updates itself",
      "4. Run sfc /scannow — corrupted system files present as 'random slowness', not crashes",
    ],
  },
  {
    title: "Free up disk space with Storage Management",
    cat: "mac",
    group: "speed",
    difficulty: 1,
    time: "5 min",
    win: "macOS",
    description: "macOS hides how full your drive really is. Storage Management shows the big offenders and can clean them automatically.",
    steps: [
      "Apple menu → About This Mac → Storage…",
      "Click 'Manage' to see what's eating space (Apps, Documents, System Data)",
      "Turn on 'Optimise Storage' so watched movies and TV get evicted automatically",
      "Remove apps you haven't opened in months — the list is usually brutal",
    ],
  },
  {
    title: "Reset NVRAM when things misbehave",
    cat: "mac",
    group: "fixes",
    difficulty: 1,
    time: "3 min",
    win: "Intel Macs",
    description: "NVRAM stores display resolution, sound and boot preferences. A reset fixes a surprising number of weird glitches.",
    steps: [
      "Shut down the Mac completely (not sleep)",
      "Press power, immediately hold Option + Command + R for about 20 seconds",
      "Release when you hear the chime or see the second startup logo",
      "Boot normally — resolution and audio glitches are often gone",
    ],
  },
  {
    title: "Keep macOS updated the safe way",
    cat: "mac",
    group: "security",
    difficulty: 1,
    time: "10 min",
    win: "macOS",
    description: "Updates fix security holes and bugs — but back up first, so a bad update is never a disaster.",
    steps: [
      "Apple menu → System Settings (or Preferences) → General → Software Update",
      "Before any major version: make a fresh Time Machine backup",
      "Install the update, then check that your daily apps still behave",
      "If something breaks after a big update, restore from Time Machine — you're covered",
    ],
  },
  {
    title: "Speed up a sluggish MacBook",
    cat: "mac",
    group: "speed",
    difficulty: 1,
    time: "5 min",
    win: "macOS",
    description: "Old MacBooks slow down for boring reasons: background apps and effects. Both are easy to tame.",
    steps: [
      "Open Activity Monitor (Cmd + Space → 'Activity')",
      "Sort by CPU and quit anything you don't recognise or need",
      "System Settings → Accessibility → Display → turn on 'Reduce motion'",
      "Close the browser tabs you've been hoarding — each one is a small app",
    ],
  },
  {
    title: "Hunt down memory hogs",
    cat: "speed",
    difficulty: 2,
    time: "10 min",
    win: "Win 10 / 11",
    description: "Full RAM is the quiet cause of most 'sluggish' complaints. Find what's eating it and put a ceiling on it.",
    steps: [
      "Ctrl + Shift + Esc → Processes tab → sort by Memory — close or End Task anything you don't need at the top",
      "Settings → Apps → Installed apps → three dots next to an app → Advanced options → Background app permissions → 'In background' off for anything that doesn't need it",
      "Hunting a leak: Win + R → perfmon → Monitoring Tools → Performance Monitor → add Process > Private Bytes — a line that climbs and never falls is your culprit; update, restart or replace that program",
      "Size the paging file: search 'View advanced system settings' → Settings → Advanced → Change → Custom size, initial 1.5× RAM in MB, max 3× (8 GB → 12,288 / 24,576) → restart",
      "Windows Security → Virus & threat protection → Full scan — malware loves to hide as a memory hog; run it monthly",
    ],
  },
  {
    title: "Make big file transfers actually fast",
    cat: "windows",
    difficulty: 1,
    time: "5 min",
    win: "Win 10 / 11",
    description: "Drag-and-drop copies files one at a time and scans every byte twice. A few settings make the same transfer feel instant.",
    steps: [
      "Check what you're copying to/from: Task Manager → Performance → Disk — it says SSD or HDD; an NVMe drive does in 15 seconds what takes an HDD three minutes",
      "Use a USB 3.x port (blue/teal plastic inside) for external drives — roughly ten times the speed of USB 2.0",
      "External drive still on FAT32? Right-click it in File Explorer → Properties to check; convert with `convert X: /fs:ntfs` from an admin prompt, or format fresh if it's empty",
      "For big moves use Robocopy instead of drag-and-drop: robocopy \"C:\\Source\" \"D:\\Dest\" /e /z /mt:16 — parallel threads, resumable, often half the time",
      "Compress first when you can (documents and code shrink 50–80%), and close background apps while the transfer runs",
    ],
  },
  {
    title: "Stop Windows tracking your location",
    cat: "security",
    difficulty: 1,
    time: "5 min",
    win: "Win 10 / 11",
    description: "Your PC knows where you are — and most apps don't need to either. Cut it off at the source.",
    steps: [
      "Settings → Privacy & Security → Location → toggle 'Location services' off for a full cutoff, or leave it on and switch off individual apps below",
      "Under 'Let apps access your location', turn off games, social apps and anything you don't recognise — most never needed it in the first place",
      "Scroll to Location history → Clear — turning tracking off doesn't delete what's already been recorded",
      "In each browser: site permissions → Location → block sites from asking (Chrome: Privacy and security → Site Settings → Location)",
      "Need it off fast for a meeting or trip? Win + A → Airplane mode kills Wi-Fi, Bluetooth and location in one tap",
    ],
  },
  {
    title: "Create a local account that doesn't phone home",
    cat: "security",
    difficulty: 2,
    time: "10 min",
    win: "Win 10 / 11",
    description: "Microsoft accounts sync your activity to their servers. A local account keeps everything on the machine — ideal for shared or guest PCs.",
    steps: [
      "Settings → Accounts → Other users → Add account, then click 'I don't have this person's sign-in info'",
      "Choose 'Add a user without a Microsoft Account' and set a username + password",
      "Faster route from an admin prompt: net user GuestName StrongPass /add — promote with net localgroup Administrators GuestName /add if needed",
      "Keep it a standard account by default; only grant Administrator when the person genuinely needs system-wide control",
      "Verify: sign out, log in as the new user, and confirm its files stay isolated from your own profile",
    ],
  },
  {
    title: "Tighten up Chrome — the 10-minute pass",
    cat: "security",
    difficulty: 1,
    time: "10 min",
    win: "Any",
    description: "Out of the box, Chrome tracks more than it needs to and keeps running apps after you close it. Ten toggles fix most of it.",
    steps: [
      "Settings → Privacy and security → Third-party cookies → 'Block third-party cookies' — kills cross-site tracking",
      "Privacy and security → Security → Safe Browsing → pick 'Enhanced protection' for real-time threat checks, not just a known-bad list",
      "Same page → Advanced → turn on 'Use secure DNS' (Cloudflare or your OS default) so your ISP can't read which sites you visit",
      "Settings → System → turn off 'Continue running background apps when Google Chrome is closed'",
      "myactivity.google.com/activity-controls → Web & App Activity → Auto-delete after 3 months — or switch it off entirely if personalization isn't worth the trail",
    ],
  },
  {
    title: "Skip paid antivirus — and keep Defender sharp",
    cat: "security",
    difficulty: 1,
    time: "15 min",
    win: "Win 10 / 11",
    description: "Most 'security suites' slow your PC down more than the malware they catch. The built-in defender is better than you think — if you switch it on properly.",
    steps: [
      "Uninstall the suite first (win+r → appwiz.cpl) — while a third-party AV is present, Defender sits in passive mode, and two engines fighting each other leaves gaps",
      "Windows Security → Virus & threat protection → Manage settings → confirm 'Real-time protection' is on",
      "App & browser control → turn on 'Reputation-based protection' so sketchy downloads get flagged before they run",
      "Device security → Core isolation details → enable Memory integrity and the Microsoft Vulnerable Driver blocklist",
      "Run a Full scan once, then monthly; for a second opinion use Microsoft Safety Scanner or MSRT — portable, no install needed",
    ],
  },
  {
    title: "Dodge bundleware when you install anything",
    cat: "cleaning",
    difficulty: 1,
    time: "5 min",
    win: "Any",
    description: "Half of every 'my PC is slow' ticket starts at an installer that checked boxes for you. One extra minute per install prevents most of it.",
    steps: [
      "Always pick 'Custom' (or 'Manual') install and read each screen — untick the toolbars, offer bundles and 'recommended' extras",
      "On a new PC, uninstall manufacturer bloat first: trial 'security', sponsor apps, utilities you'll never open",
      "Avoid download managers, Wi-Fi boosters and registry cleaners entirely — they're adware with extra steps; your browser's built-in downloader is fine",
      "For ad blocking use uBlock Origin instead of extensions that run their own ad networks or inject into checkout pages",
      "Prefer free/open-source alternatives to paid software over cracked copies — a 'free' installer from a dodgy site is how keyloggers arrive",
    ],
  },
  {
    title: "Run drive optimization the safe way",
    cat: "maintenance",
    difficulty: 1,
    time: "5 min",
    win: "Win 10 / 11",
    description: "Defragmenting an SSD is actively harmful; skipping it on an HDD leaves speed on the table. Windows has one tool that does both correctly.",
    steps: [
      "Search 'Defragment and optimize drives' (or win+r → dfrgui) — it lists every drive with its type",
      "HDDs: click Optimize to defrag; SSDs: the same button runs TRIM instead, which is what they actually need",
      "Click 'Change settings' → enable 'Optimize on a schedule' (weekly for HDDs, monthly for SSDs) and let Windows do it overnight",
      "Keep 10–20% of your main drive free — a full disk slows everything down, including the pagefile",
    ],
  },
  {
    title: "Master the keyboard shortcuts that save hours",
    cat: "windows",
    difficulty: 1,
    time: "5 min",
    win: "Win 10 / 11",
    description: "You're probably doing 90% of your work with the mouse. Ten keys below will shave minutes off every single day.",
    steps: [
      "Win + V opens clipboard history — paste any of your last ~25 copies, not just the latest one (enable it on first use)",
      "Win + Shift + S snips exactly what you want to capture instead of a full-screen screenshot",
      "Alt + Tab cycles open apps; hold Alt and mash Tab to preview them — faster than hunting the taskbar",
      "Win + D shows your desktop instantly (press again to bring everything back) — perfect for a quick glance away from work",
      "Win + E opens File Explorer, Win + I opens Settings, Win + L locks your PC when you step out of the room",
    ],
  },
  {
    title: "Install PowerToys — Microsoft's free utility pack",
    cat: "windows",
    difficulty: 1,
    time: "10 min",
    win: "Win 10 / 11",
    description: "Microsoft's own free toolkit fixes the little things Windows gets wrong. It's official, safe and better than most paid utilities.",
    steps: [
      "Get it from the Microsoft Store (search 'PowerToys') or GitHub — never a third-party download site",
      "PowerToys Run (Alt + Space): a fast app launcher that also does math and unit conversion",
      "FancyZones: snap windows into custom layouts — ideal for dual-monitor setups",
      "Awake keeps the PC from sleeping while you render or download; Color Picker samples any on-screen colour with Win + Shift + C",
      "Text Extractor (Win + Shift + T): grab text straight out of screenshots, including PDFs and video frames",
    ],
  },
  {
    title: "Lock down your home Wi-Fi properly",
    cat: "security",
    difficulty: 2,
    time: "15 min",
    win: "Any",
    description: "Your router's default name is a map for attackers — it tells them the make, model and which firmware bugs to try. Fifteen minutes fixes all of that.",
    steps: [
      "Log into your router (usually 192.168.0.1 or 192.168.1.1) and change the admin password first — it's the door everything else goes through",
      "Rename the network (SSID) to something that doesn't reveal you: no house numbers, names or 'SmithFamily'",
      "Set a strong Wi-Fi passphrase (12+ random characters work well) and use WPA3 if your router supports it, otherwise WPA2 — never WEP or open",
      "Turn off WPS if you can see the setting — it's been crackable for years",
      "Create a guest network for visitors and smart-home gear so they're walled off from your PC",
    ],
  },
  {
    title: "Stop emailing passwords and secrets",
    cat: "security",
    difficulty: 1,
    time: "10 min",
    win: "Any",
    description: "Email is not a vault. Passwords, OTP codes and API keys sitting in an inbox are the easiest win a hacker can get.",
    steps: [
      "Move everything into a password manager (Bitwarden free, 1Password) — one master password to remember, everything else generated for you",
      "Turn on two-factor authentication for email, banking and anything that matters; prefer an authenticator app over SMS where possible",
      "Search your inbox for 'password', 'OTP' and 'verification', then delete those threads once the credentials are moved",
      "If a service has no 2FA option at all, treat that as a signal to find one that does",
    ],
  },
  {
    title: "Turn on full-disk encryption (BitLocker)",
    cat: "security",
    difficulty: 1,
    time: "5 min",
    win: "Win 10 / 11",
    description: "If your laptop is stolen or lost, an unencrypted drive is just a USB stick with someone else's life on it. BitLocker makes the data unreadable without your sign-in.",
    steps: [
      "Settings → Privacy & Security → Device encryption — if it says 'On', you're already covered (common on laptops)",
      "If it's off, flip it on; Windows encrypts in the background while you keep working",
      "Desktop or older machine? Search 'Manage BitLocker' and turn it on for your main drive instead",
      "Write down the recovery key and store it somewhere that isn't this PC (your Microsoft account does this automatically)",
    ],
  },
  {
    title: "Make your laptop battery last longer",
    cat: "maintenance",
    difficulty: 1,
    time: "10 min",
    win: "Any",
    description: "Batteries age from heat and from sitting at 100% all day. A few settings slow the ageing down noticeably.",
    steps: [
      "Settings → System → Power & battery → turn on Battery saver below 20%, or set it to kick in earlier if you're always on the move",
      "Enable Optimised charging in your laptop maker's tool (Lenovo Vantage, MyASUS, Dell Power Manager) so the machine stops holding 100% overnight",
      "Keep it cool: run on a hard surface, not a duvet; dust out the vents once or twice a year (see the overheating fix)",
      "Check health any time: Task Manager → Performance → Battery shows wear and design capacity — under ~80% of design is when replacement starts to make sense",
    ],
  },
  {
    title: "Fix a blue screen (BSOD) without panicking",
    cat: "maintenance",
    difficulty: 2,
    time: "30 min",
    win: "Win 10 / 11",
    description: "A blue screen looks dramatic but it's usually Windows protecting itself from a bad driver or a flaky stick of RAM. The stop code tells you which.",
    steps: [
      "Read the stop code at the bottom (e.g. DRIVER_IRQL_NOT_LESS_OR_EQUAL) and search that exact string — generic 'BSOD fix' articles are mostly noise",
      "If it started after an update or a new driver, roll back: Settings → Windows Update → Update history → Uninstall updates, or Device Manager → Roll back driver on the suspect device",
      "Event Viewer → Windows Logs → System: look for red errors in the minutes before each crash — they name the culprit file",
      "Run Windows Memory Diagnostic (search 'mdsched') to rule out bad RAM; a failing stick shows up as random BSODs across different drivers",
    ],
  },
  {
    title: "No sound? The four-minute fix",
    cat: "windows",
    difficulty: 1,
    time: "4 min",
    win: "Win 10 / 11",
    description: "Most 'my PC has no audio' tickets are the wrong output device selected after a driver update or a plugged-in headset.",
    steps: [
      "Click the speaker icon in the taskbar → check the volume slider and that you're not muted; click the arrow to pick the right output (speakers vs headphones vs HDMI)",
      "Settings → System → Sound → open Volume mixer — sometimes one app is at zero while everything else looks fine",
      "Update or roll back the audio driver: Device Manager → Sound controllers → right-click your device → Update driver (or Roll back if it broke after an update)",
      "Restart the audio stack: Win + R → services.msc → find 'Windows Audio' → Restart; do the same for 'Windows Audio Endpoint Builder'",
    ],
  },
  {
    title: "Organise your work with virtual desktops",
    cat: "windows",
    difficulty: 1,
    time: "5 min",
    win: "Win 10 / 11",
    description: "One giant taskbar full of thirty apps is where focus goes to die. Windows has had real multi-desktop support forever — most people never find it.",
    steps: [
      "Win + Ctrl + D creates a new virtual desktop; Win + Ctrl + Left/Right switches between them",
      "Task View (Win + Tab) shows all of them at once — drag windows between desktops from there",
      "Give each one a job: work, research, music/games — your brain stops context-switching when the taskbar does",
      "Win + Ctrl + F4 closes the current desktop; right-click its thumbnail in Task View to rename it",
    ],
  },
  {
    title: "Slow internet? Run the five-minute test",
    cat: "windows",
    difficulty: 1,
    time: "10 min",
    win: "Any",
    description: "Before you blame your ISP, prove where the slowdown actually is. Five minutes of testing separates 'bad router' from 'bad line'.",
    steps: [
      "Close everything bandwidth-hungry (downloads, cloud sync, video calls), then run a speed test on speedtest.net — note download, upload and ping",
      "Test wired vs Wi-Fi: plug in with Ethernet and re-test. A big gap means your router or its placement is the problem, not the line",
      "Move closer to the router or switch to the 5 GHz band (faster, shorter range); keep it off a shelf behind metal cabinets",
      "Reboot the router — months of uptime clog its memory; if speed returns for a week and then sags again, schedule a weekly reboot",
      "Still slow on both wired and Wi-Fi? That's your ISP's problem now — and you have numbers to quote them",
    ],
  },
  {
    title: "Force-quit a frozen app",
    cat: "mac",
    group: "fixes",
    difficulty: 1,
    time: "1 min",
    win: "macOS",
    description: "A spinning beachball means the app is stuck, not your Mac. Kill it cleanly without restarting everything.",
    steps: [
      "Cmd + Option + Esc opens the Force Quit window — pick the app and hit Force Quit",
      "Or right-click (or Control-click) its Dock icon → Force Quit",
      "If Finder itself is frozen: open Activity Monitor, select 'Finder' and hit the ⓧ button — it relaunches automatically",
    ],
  },
  {
    title: "Stop apps from launching at login",
    cat: "mac",
    group: "speed",
    difficulty: 1,
    time: "5 min",
    win: "macOS",
    description: "Every app that starts with your Mac steals seconds from boot and RAM all day long. Most of them don't need to be there.",
    steps: [
      "System Settings → General → Login Items — remove anything you don't consciously want at startup (the minus button)",
      "Scroll down to 'Allow in the Background' and switch off apps that don't genuinely need background work",
      "Some apps hide their setting inside themselves (Slack, Discord, 1Password all have a 'Launch at login' toggle) — check there too if it sneaks back",
    ],
  },
  {
    title: "Keep 10% of your disk free",
    cat: "mac",
    group: "speed",
    difficulty: 1,
    time: "10 min",
    win: "macOS",
    description: "macOS needs headroom for swap and caches. Under about 10% free space, everything — including Time Machine — starts to crawl.",
    steps: [
      "Apple menu → About This Mac → Storage… → Manage — sort categories by size and delete what you don't need (Apps, Documents, 'Other')",
      "Sort items by date last used — the oldest offenders are usually safe to move to an external drive",
      "Empty the Trash (Finder → Empty Trash) and clear out Downloads; set Finder → Settings → Advanced → 'Remove items from the Trash after 30 days'",
      "Photos library is huge? Photos → Settings → iCloud → Optimise Mac Storage keeps full-resolution copies in the cloud",
    ],
  },
  {
    title: "Tame Spotlight indexing on extra drives",
    cat: "mac",
    group: "speed",
    difficulty: 2,
    time: "5 min",
    win: "macOS",
    description: "Spotlight re-indexes every drive it can see. On an older Mac with a big external HDD, that background work is often your whole 'slowness'.",
    steps: [
      "System Settings → Siri & Spotlight → Spotlight Privacy (older macOS: the Spotlight tab in System Preferences)",
      "Add any external or backup drives you don't need to search — they stop being indexed and the disk light goes quiet",
      "Keep your main drive indexed; if search results feel stale, remove it from the list and re-add it to force a clean rebuild",
    ],
  },
  {
    title: "Fix a Mac that won't start up",
    cat: "mac",
    group: "fixes",
    difficulty: 2,
    time: "30 min",
    win: "All Macs",
    description: "A black screen at boot is scary, but macOS has a recovery mode that fixes most of it without erasing anything.",
    steps: [
      "Apple Silicon (M1–M4): press and hold the power button until 'Loading startup options' appears → Options → Continue",
      "Intel Macs: restart and immediately hold Cmd + R until the Apple logo or a spinning globe shows",
      "In Recovery, open Disk Utility → select your main drive → First Aid — this fixes most boot problems on its own",
      "If that fails, choose 'Reinstall macOS' from the recovery menu — it reinstalls over your existing system and keeps your files",
    ],
  },
  {
    title: "Run First Aid on external drives",
    cat: "mac",
    group: "fixes",
    difficulty: 1,
    time: "10 min",
    win: "macOS",
    description: "External drives fail quietly — files vanish, copies stall. Disk Utility's First Aid catches most problems while they're still fixable.",
    steps: [
      "Open Disk Utility (Cmd + Space → 'Disk Utility'), select the drive in the sidebar and hit First Aid → Start",
      "If it reports errors it can't repair, back up what you can immediately — that drive is on borrowed time",
      "Mac-only drives should be APFS or Mac OS Extended; Windows-shared drives should be exFAT (check under 'Info' after selecting)",
      "Run First Aid monthly on any drive holding important data — ten minutes now beats a data-recovery quote later",
    ],
  },
  {
    title: "Keep your Mac battery healthy",
    cat: "mac",
    group: "fixes",
    difficulty: 1,
    time: "5 min",
    win: "macOS",
    description: "Lithium batteries age from heat and from sitting at full charge. macOS has one setting that quietly slows both down.",
    steps: [
      "System Settings → Battery → make sure Optimised Battery Charging is on — it learns your routine and holds below 100% until you usually unplug",
      "Check health any time: System Settings → Battery → Battery Health — 'Normal' with a good max capacity means you're fine",
      "Avoid sustained heat: no duvets, no direct sun while charging; a hot MacBook is an ageing battery",
      "Apple Silicon Macs handle charge cycles well — if the battery's health drops below ~80%, that's the point to consider service",
    ],
  },
  {
    title: "Set up Time Machine properly",
    cat: "mac",
    group: "security",
    difficulty: 1,
    time: "20 min",
    win: "macOS",
    description: "Time Machine is the closest thing macOS has to 'undo' for your whole computer. Twenty minutes now saves a disaster later.",
    steps: [
      "Connect an external drive (500 GB+ recommended), then System Settings → General → Time Machine → Add Backup Disk",
      "Pick the drive and let it run the first full backup — it can take hours, so start it before bed",
      "After that it runs automatically hourly; you get version-by-version history of every file in Finder (Cmd + Option click any file to browse its past versions)",
      "Test a restore once: open Time Machine → pick an old folder → Restore. A backup you've never restored is a rumour",
    ],
  },
  {
    title: "Turn on FileVault full-disk encryption",
    cat: "mac",
    group: "security",
    difficulty: 1,
    time: "3 min",
    win: "macOS",
    description: "If your Mac is stolen or lost, FileVault is the difference between 'inconvenience' and 'identity theft'. It's one click.",
    steps: [
      "System Settings → Privacy & Security → FileVault → Turn On FileVault Protection",
      "Choose whether to let iCloud unlock it (convenient) or keep a recovery key — if you pick the key, store it somewhere that isn't this Mac",
      "Encryption happens in the background over a few hours; your Mac keeps working normally meanwhile",
    ],
  },
  {
    title: "Open apps blocked by Gatekeeper",
    cat: "mac",
    group: "fixes",
    difficulty: 1,
    time: "2 min",
    win: "macOS",
    description: "'Cannot be opened because the developer cannot be verified' usually means a small indie app, not malware. Here's the safe way past it.",
    steps: [
      "Right-click (or Control-click) the app in Finder → Open → confirm 'Open' in the dialog — this only works for that first launch",
      "If that option isn't there: System Settings → Privacy & Security → scroll to the bottom → 'Open Anyway' next to the blocked-app message",
      "Only do this for apps you actually trust from a source you know — Gatekeeper exists because unsigned software is where malware hides",
    ],
  },
  {
    title: "Fix slow Wi-Fi on your Mac",
    cat: "mac",
    group: "fixes",
    difficulty: 1,
    time: "10 min",
    win: "macOS",
    description: "Before you blame the router or the ISP, rule out the Mac side of the connection in ten minutes.",
    steps: [
      "Toggle Wi-Fi off and back on (menu bar → Control Center), then click the Wi-Fi icon → Details → 'Forget This Network' and reconnect with the password — this clears a stale handshake",
      "Check you're on 5 GHz if your router offers it (often named like 'Home-5G') — faster, less congested, shorter range",
      "Reboot the router: months of uptime clog its memory; if speed returns for a week and then sags again, schedule a weekly reboot",
      "Test wired vs Wi-Fi with an Ethernet adapter or USB-C hub — if wired is fast and Wi-Fi isn't, it's placement or interference, not your line",
    ],
  },
  {
    title: "Give Safari a proper clean-out",
    cat: "mac",
    group: "speed",
    difficulty: 1,
    time: "5 min",
    win: "macOS",
    description: "Safari accumulates website data, extensions and cache that quietly slow every page down. A five-minute pass brings back the speed you had in January.",
    steps: [
      "Safari → Settings (or Preferences) → Privacy → Manage Website Data → Remove All — this clears cookies and cached files for every site",
      "Same settings window → Extensions tab → disable anything you haven't used in months; each one runs on every page load",
      "Close the tabs you've been hoarding — Safari keeps a live process per tab, and 40 tabs is 40 mini-apps",
      "Still sluggish? Settings → Advanced → tick 'Show Develop menu in menu bar', close all windows, then use Develop → Empty Caches",
    ],
  },
  {
    title: "Pick an SSD that's actually fast",
    cat: "hardware",
    difficulty: 1,
    time: "5 min",
    win: "Any",
    description: "Not all solid-state drives are equal. The label tells you almost nothing — the interface and the NAND type do.",
    steps: [
      "For your main drive, buy NVMe (M.2) — it's 3–5× faster than SATA SSDs and costs about the same per GB now",
      "Avoid QLC drives for daily use: they're cheap but slow down badly once full; TLC is the sweet spot for price and endurance",
      "If your case only has a 2.5\" bay, a SATA SSD is still a massive upgrade over any HDD — don't skip it because it's 'only' SATA",
      "Check the drive's sustained write speed if you move big files (video, VMs) — that number matters more than peak read speed",
    ],
  },
  {
    title: "Size your PSU before the next upgrade",
    cat: "hardware",
    difficulty: 2,
    time: "15 min",
    win: "Any",
    description: "A power supply that's too small is the quiet cause of random shutdowns under load. Sizing it right takes one calculator and ten minutes.",
    steps: [
      "Add up your parts' typical draw (CPU + GPU are 80% of it) — be honest about the GPU you're planning, not the one you have",
      "Buy ~30% headroom over that total: a 450 W system wants a 600–650 W unit, which also runs cooler and quieter at part load",
      "Pick 80 Plus Bronze or better — it's a minimum efficiency floor, not a quality award, but it filters out the worst",
      "Prefer native cables (the PSU maker's own) over adapters for your GPU; one good cable beats two daisy-chained ones",
    ],
  },
  {
    title: "Fix a hot PC for good: the airflow pass",
    cat: "hardware",
    difficulty: 2,
    time: "45 min",
    win: "Any",
    description: "Dust cleaning is a band-aid. The real fix is airflow: cool air in one side, hot air out the other, with nothing blocking either.",
    steps: [
      "Map your case: front and bottom fans pull cool air IN (labels face out), rear and top fans push hot air OUT",
      "If you have no exhaust fan at all, add one at the rear — a single intake with zero exhaust just shuffles warm air around",
      "Keep 5–10 cm of clearance behind the case; a PC shoved against a wall re-inhales its own heat",
      "Clean the dust filters (front/bottom) every few months and route cables out of the front intake path",
      "Verify with HWiNFO64: idle CPU under 45°C and GPU under 50°C means the pass worked",
    ],
  },
];

// Category display names used in the card badge
const CAT_LABELS = {
  mac: "Mac",
  speed: "Speed",
  windows: "Windows",
  gaming: "Gaming",
  cleaning: "Cleaning",
  maintenance: "Maintenance",
  hardware: "Hardware",
  security: "Security",
};

/* URL slug for each tip's detail page (tips/<slug>.html).
   Used by script.js (cards) and build-tips.js (generator) — keep identical. */
function tipSlug(title) {
  return String(title)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
